import { useEffect, useState } from "react";
import type { DoorEvent, Notification, Source } from "../api";
import { api, formatDateTime, newestFirst, useDoorState } from "../api";

const KIND_LABEL: Record<string, string> = {
  package_arrived: "Package arrived",
  package_reminder: "Package reminder",
  package_missing: "Possible missing package",
  unusual_hour: "Unusual-hour activity",
};

const SOURCE_TITLE: Record<Source, string> = {
  bedrock: "Scene described by the Bedrock vision model",
  stub: "Automatic estimate from the local detector (vision model unavailable)",
  rules: "Generated by a time-based rule",
};

function SourceBadge({ source }: { source: Source }) {
  return (
    <span className={`badge badge-${source}`} title={SOURCE_TITLE[source]}>
      <span className="sr-only">Source: </span>
      {source}
    </span>
  );
}

const eventSource = (e: DoorEvent): Source => e.description_source ?? "rules";

function Score({ value }: { value: number }) {
  const level = value >= 0.7 ? "high" : value > 0 ? "mid" : "low";
  return (
    <span className={`score score-${level}`}>
      Unusual-hour score <strong>{value.toFixed(2)}</strong>
      <meter min={0} max={1} low={0.3} high={0.7} optimum={0} value={value} aria-hidden="true" />
    </span>
  );
}

function AlertCard({ n, event, tz }: { n: Notification; event?: DoorEvent; tz: string }) {
  const explanation = event?.unusual_explanation && n.kind !== "unusual_hour" ? event.unusual_explanation : null;
  return (
    <li className={`alert alert-${n.kind}`}>
      {event?.snapshot_url ? (
        <img className="thumb" src={event.snapshot_url} alt={event.accessible_description ?? `Snapshot for ${n.kind}`} />
      ) : (
        <div className="thumb thumb-empty" aria-hidden="true">no image</div>
      )}
      <div className="alert-body">
        <div className="alert-head">
          <h3>{KIND_LABEL[n.kind] ?? n.kind}</h3>
          <SourceBadge source={n.source} />
          <time dateTime={n.sim_ts}>{formatDateTime(n.sim_ts, tz)}</time>
        </div>
        <p>{n.text}</p>
        {explanation && <p className="muted">{explanation}</p>}
        {event?.package_check && <p className="muted">Package check: {event.package_check}</p>}
        {event?.unusual_score != null && <Score value={event.unusual_score} />}
      </div>
    </li>
  );
}

export default function Caregiver() {
  const { state, error, refresh } = useDoorState();
  const [status, setStatus] = useState("");
  const [setTime, setSetTime] = useState("");

  useEffect(() => {
    document.title = "Caregiver — DoorSight";
  }, []);

  const tz = state?.clock.tz ?? "UTC";
  const events = new Map((state?.events ?? []).map((e) => [e.event_id, e]));
  const alerts = newestFirst((state?.notifications ?? []).filter((n) => n.audience === "caregiver"));
  const residentMsgs = newestFirst((state?.notifications ?? []).filter((n) => n.audience === "resident"));
  const activity = newestFirst(state?.events ?? []);
  const packages = [...(state?.packages ?? [])].reverse();

  async function run(label: string, fn: () => Promise<string>) {
    setStatus(`${label}…`);
    try {
      setStatus(await fn());
    } catch (e) {
      setStatus(`${label} failed: ${e instanceof Error ? e.message : e}`);
    }
    await refresh();
  }

  const clockAction = (label: string, body: Parameters<typeof api.clock>[0]) =>
    run(label, async () => {
      const r = await api.clock(body);
      const reminders = r.reminders_queued.length ? ` — ${r.reminders_queued.length} reminder(s) queued` : "";
      return `Demo clock now ${formatDateTime(r.sim_now, r.tz)}${reminders}`;
    });

  const simulate = (type: "package" | "vehicle" | "motion") =>
    run(`Simulating ${type}`, async () => {
      const r = await api.simulate(type);
      return `Accepted ${r.event_id}: capturing ~20 s of live video, then analysing. Tip: ${r.presenter_hint}.`;
    });

  return (
    <div className="caregiver">
      <header className="c-header">
        <div>
          <h1>DoorSight · Caregiver</h1>
          <p className="muted">Front door of the home you look after</p>
        </div>
        {state && (
          <div className="c-clock" role="group" aria-label="Demo clock">
            <span className="muted">Demo time</span>
            <strong>{formatDateTime(state.clock.sim_now, tz)}</strong>
            <span className="muted">offset {(state.clock.offset_s / 3600).toFixed(2)} h</span>
          </div>
        )}
      </header>

      <main className="c-grid">
        <section className="panel controls" aria-labelledby="controls-h">
          <h2 id="controls-h">Demo controls</h2>
          <div className="row" role="group" aria-label="Change the demo clock">
            <button type="button" onClick={() => clockAction("Advancing 1 h", { advance_hours: 1 })}>+1 h</button>
            <button type="button" onClick={() => clockAction("Advancing 3 h", { advance_hours: 3 })}>+3 h</button>
            <label className="inline">
              <span>Set time</span>
              <input type="datetime-local" value={setTime} onChange={(e) => setSetTime(e.target.value)} />
            </label>
            <button type="button" disabled={!setTime} onClick={() => clockAction("Setting time", { set: setTime })}>
              Set
            </button>
            <button type="button" className="ghost" onClick={() => clockAction("Resetting", { reset: true })}>
              Real time
            </button>
          </div>
          <div className="row" role="group" aria-label="Simulate a Ring event">
            <button type="button" className="sim" onClick={() => simulate("package")}>Simulate package</button>
            <button type="button" className="sim" onClick={() => simulate("vehicle")}>Simulate vehicle</button>
            <button type="button" className="sim" onClick={() => simulate("motion")}>Simulate motion</button>
          </div>
          <p className="muted small">Click the matching event in the Ring Playground first so the camera shows that scene.</p>
          <p className="status" role="status" aria-live="polite">{status}</p>
          {error && <p className="error" role="alert">Backend unreachable: {error}</p>}
        </section>

        <section className="panel alerts" aria-labelledby="alerts-h">
          <h2 id="alerts-h">Alerts <span className="count">{alerts.length}</span></h2>
          {alerts.length ? (
            <ul className="alert-list">
              {alerts.map((n) => <AlertCard key={n.id} n={n} event={n.event_id ? events.get(n.event_id) : undefined} tz={tz} />)}
            </ul>
          ) : (
            <p className="muted">No alerts.</p>
          )}
        </section>

        <section className="panel" aria-labelledby="pkg-h">
          <h2 id="pkg-h">Packages</h2>
          {packages.length ? (
            <ul className="plain">
              {packages.map((p) => (
                <li key={p.id} className="pkg">
                  <span className={`pill pill-${p.status}`}>{p.status.replace("_", " ")}</span>
                  <span>arrived {formatDateTime(p.arrived_sim_ts, tz)}</span>
                  {p.reminded_sim_ts && <span className="muted">reminded {formatDateTime(p.reminded_sim_ts, tz)}</span>}
                  {p.resolved_sim_ts && <span className="muted">resolved {formatDateTime(p.resolved_sim_ts, tz)}</span>}
                </li>
              ))}
            </ul>
          ) : (
            <p className="muted">No packages yet.</p>
          )}
          <h2 id="msgs-h">Messages to the resident</h2>
          {residentMsgs.length ? (
            <ul className="plain msgs" aria-labelledby="msgs-h">
              {residentMsgs.map((n) => (
                <li key={n.id}>
                  <SourceBadge source={n.source} /> <time dateTime={n.sim_ts}>{formatDateTime(n.sim_ts, tz)}</time>
                  <div>{n.text}</div>
                </li>
              ))}
            </ul>
          ) : (
            <p className="muted">None yet.</p>
          )}
        </section>

        <section className="panel activity" aria-labelledby="act-h">
          <h2 id="act-h">Door activity</h2>
          {activity.length ? (
            <table>
              <thead>
                <tr>
                  <th scope="col">Time</th>
                  <th scope="col">Event</th>
                  <th scope="col">Seen</th>
                  <th scope="col">Package check</th>
                  <th scope="col">Unusual</th>
                  <th scope="col">Source</th>
                </tr>
              </thead>
              <tbody>
                {activity.map((e) => (
                  <tr key={e.event_id}>
                    <td><time dateTime={e.sim_ts}>{formatDateTime(e.sim_ts, tz)}</time></td>
                    <td>{e.event_type}</td>
                    <td>
                      {[e.package_seen && "package", e.vehicle_seen && "vehicle", e.person_seen && "person"]
                        .filter(Boolean).join(", ") || "—"}
                    </td>
                    <td>{e.package_check ?? "—"}</td>
                    <td>{e.unusual_score != null ? e.unusual_score.toFixed(2) : "—"}</td>
                    <td><SourceBadge source={eventSource(e)} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <p className="muted">No events yet.</p>
          )}
        </section>
      </main>
    </div>
  );
}
